### ISSUE TITLE
Api >  Connect Chrome Ext to API

### ISSUE THREAD

**Issue by Belfast82** [Belfast82/Streamskip#12]
Description:
The Chrome extension will need to be updated to read from the API. It should send up a Netflix Id to filter all the video entries and return only those entries. The front-end should continue to display the data and not require additional work after pointing to the new data source.

Acceptance Criteria
The Chrome extension will make API calls to the hosted cloud service. Only the current Netflix video data will be shown to the user. When viewing a different video, a new API will will be made for that data and only for that data.

**Comment by esaith** [comment]
Get latest from git. Follow the below directions for a reminder. If you have questions please let me know since the directions may need to be updated.
https://github.com/Belfast82/Streamskip/wiki/Get-latest-from-Github-and-test-update

During the PoC, hard coded values then Azure blob storage JSON file was used to hydrate the data for the chrome extension. This was good for the PoC but not great for adding dynamic data from multiple users. Having an API allows adding data to be safe and secure (at some point) by giving an interface to the data after verifying the user. Once authentication is added, users will not be able to add or edit data without being logging in. Authentication will not be required at the moment for pulling the data.

Testing Notes.
In Chrome, open DevTools by pressing F12. Go to the Network tab, then refresh the page. There should be an API call to https://skipstream.azurewebsites.net. Open the Preview tab on the API call. This will show the JSON for the specific Netflix video.

**Comment by Belfast82** [comment]
Passed by QA.
